### PR TITLE
Lib update and .gitignore

### PR DESCRIPTION
**Pull request by jcgruenhage**
Updated the mp3agic lib from a snapshot to the most recent release

### CODE REVIEW

**Comment by jcgruenhage** [comment]
added gitignore according to the linux, android, java and intellij addons

**Comment by jcgruenhage** [comment]
I put this pull request here, because it seems that you are more active than @arcus92 at the moment

**Comment by ddonuts4** [comment]
Looks good, especially the .gitignore

**Comment by ddonuts4** [comment]
I don't plan to do that much work on this project, so I added you as a collaborator. If you want to do anything else feel free.

**Comment by jcgruenhage** [comment]
Thank you ^^

**Pull request merged**
